const allCities = [
    "Mexico City",
    "New York City",
    "Los Angeles",
    "Chicago",
    "Toronto",
    "Brooklyn",
    "Houston",
    "Queens",
    "Santo Domingo",
    "Havana",
    "Iztapalapa",
    "Ecatepec de Morelos",
    "Montreal",
    "Philadelphia",
    "Phoenix",
    "Guadalajara",
    "Manhattan",
    "San Antonio",
    "Puebla",
    "San Diego",
    "The Bronx",
    "Juarez",
    "Tijuana",
    "Dallas",
    "Leon de los Aldama",
    "Port-au-Prince",
    "Santiago de los Caballeros",
    "Gustavo Adolfo Madero",
    "Zapopan",
    "Monterrey",
    "Ciudad Nezahualcoyotl",
    "San Jose",
    "Calgary",
    "Guatemala City",
    "Managua",
    "Kingston",
    "Austin",
    "Jacksonville",
    "San Francisco",
    "Tegucigalpa",
    "Columbus",
    "Fort Worth",
    "Indianapolis",
    "Charlotte",
    "Ottawa",
    "Chihuahua",
    "Naucalpan de Juarez",
    "Merida",
    "Alvaro Obregon",
    "San Luis Potosi",
    "Aguascalientes",
    "Hermosillo",
    "Edmonton",
    "Saltillo",
    "Santo Domingo Oeste",
    "Santo Domingo Este",
    "Mexicali",
    "Seattle",
    "Denver",
    "El Paso",
    "Detroit",
    "Culiacan",
    "Guadalupe",
    "Acapulco de Juarez",
    "Mississauga",
    "Boston",
    "Memphis",
    "Tlalnepantla",
    "New South Memphis",
    "North York",
    "Portland",
    "Winnipeg",
    "Oklahoma City",
    "Cancun",
    "Santiago de Queretaro",
    "Las Vegas",
    "Baltimore",
    "Coyoacan",
    "Santa Maria Chimalhuacan",
    "Torreon",
    "Washington, D.C.",
    "Milwaukee",
    "Scarborough",
    "Morelia",
    "Reynosa",
    "New Kingston",
    "Tlaquepaque",
    "Tlalpan",
    "South Boston",
    "Albuquerque",
    "Santiago de Cuba",
    "Tuxtla",
    "Cuauhtemoc",
    "Tucson",
    "Nashville",
    "Quebec",
    "San Salvador",
    "Fresno",
    "Hamilton",
    "Victoria de Durango",
    "Sacramento",
    "San Pedro Sula",
    "Toluca",
    "Ciudad Lopez Mateos",
    "Cuautitlan Izcalli",
    "Kansas City",
    "Long Beach",
    "Mixco",
    "Mesa",
    "Staten Island",
    "Ciudad Apodaca",
    "Atlanta",
    "Colorado Springs",
    "Virginia Beach",
    "Raleigh",
    "Heroica Matamoros",
    "Omaha",
    "San Nicolas de los Garza",
    "Carrefour",
    "Miami",
    "Brampton",
    "Venustiano Carranza",
    "Veracruz",
    "Xalapa de Enriquez",
    "Oakland",
    "San Juan",
    "Azcapotzalco",
    "Minneapolis",
    "Tonala",
    "Panama",
    "Xochimilco",
    "Villa Nueva",
    "Tulsa",
    "Surrey",
    "Wichita",
    "New Orleans",
    "Arlington",
    "Cleveland",
    "Benito Juarez",
    "Iztacalco",
    "Delmas",
    "Mazatlan",
    "Irapuato",
    "Laval",
    "Nuevo Laredo",
    "Bakersfield",
    "Miguel Hidalgo",
    "Honolulu",
    "Tampa",
    "Aurora",
    "Halifax",
    "Xico",
    "Benito Juarez",
    "Villahermosa",
    "Ciudad General Escobedo",
    "Anaheim",
    "Etobicoke",
    "Camaguey",
    "London",
    "Celaya",
    "West Raleigh",
    "Cuernavaca",
    "Santa Ana",
    "San Jose",
    "Tepic",
    "Soyapango",
    "Corpus Christi",
    "Riverside",
    "Ixtapaluca",
    "San Miguelito",
    "Holguin",
    "St. Louis",
    "Lexington-Fayette",
    "Tampico",
    "Stockton",
    "Ciudad Victoria",
    "Tlahuac",
    "Pittsburgh",
    "Anchorage",
    "Ciudad Obregon",
    "Okanagan",
    "Cincinnati",
    "Victoria",
    "Meads",
    "Ironville",
    "Henderson",
    "Greensboro",
    "Saint Paul",
    "Plano",
    "Petionville",
    "Newark",
    "Nicolas Romero",
    "Toledo",
    "Ensenada",
    "Windsor",
    "Coacalco",
    "Lincoln",
    "Guantanamo",
    "Orlando",
    "Santa Catarina",
    "Chula Vista",
    "Uruapan",
    "Jersey City",
    "Markham",
    "Chandler",
    "Fort Wayne",
    "Buffalo",
    "Durham",
    "Gomez Palacio",
    "St. Petersburg",
    "Irvine",
    "Los Mochis",
    "Pachuca de Soto",
    "Laredo",
    "Oaxaca",
    "Soledad de Graciano Sanchez",
    "Santa Clara",
    "Colonia del Valle",
    "Port-de-Paix",
    "Lubbock",
    "Madison",
    "Tehuacan",
    "Oshawa",
    "Gilbert",
    "Norfolk",
    "Louisville",
    "Ojo de Agua",
    "Gatineau",
    "Reno",
    "Winston-Salem",
    "Glendale",
    "Vaughan",
    "Magdalena Contreras",
    "Hialeah",
    "Garland",
    "Scottsdale",
    "Irving",
    "Coatzacoalcos",
    "Chesapeake",
    "North Las Vegas",
    "Kitchener",
    "Fremont",
    "Longueuil",
    "Croix-des-Bouquets",
    "Baton Rouge",
    "Nassau Bahamas",
    "Diez de Octubre",
    "Lexington",
    "Paradise",
    "Campeche",
    "Richmond",
    "San Pedro de Macoris",
    "San Bernardino",
    "Monclova",
    "La Paz",
    "Spokane",
    "Nogales",
    "Birmingham",
    "Modesto",
    "Des Moines",
    "Arroyo Naranjo",
    "Rochester",
    "La Romana",
    "Maryvale",
    "Tacoma",
    "Arlington",
    "Fontana",
    "Oxnard",
    "Buenavista",
    "Moreno Valley",
    "Las Tunas",
    "Bayamon",
    "Puerto Vallarta",
    "Burnaby",
    "Tapachula",
    "Fayetteville",
    "Huntington Beach",
    "Yonkers",
    "Glendale",
    "Aurora",
    "Montgomery",
    "Columbus",
    "Ladner",
    "Saskatoon",
    "Amarillo",
    "Little Rock",
    "Akron",
    "Ciudad Madero",
    "Shreveport",
    "Grand Rapids",
    "Mobile",
    "Salt Lake City",
    "Bayamo",
    "Huntsville",
    "Tallahassee",
    "Sunrise Manor",
    "Boyeros",
    "Grand Prairie",
    "Chilpancingo",
    "Pinar del Rio",
    "Cienfuegos",
    "Overland Park",
    "Richmond Hill",
    "Knoxville",
    "Poza Rica de Hidalgo",
    "Worcester",
    "Brownsville",
    "Newport News",
    "Santa Clarita",
    "Barrie",
    "Richmond",
    "Harlem",
    "Nepean",
    "Providence",
    "Fort Lauderdale",
    "East Flatbush",
    "Spring Valley",
    "Habana del Este",
    "Santa Ana",
    "Chattanooga",
    "Regina",
    "Tempe",
    "Oceanside",
    "Bella Vista",
    "Garden Grove",
    "Rancho Cucamonga",
    "Cape Coral",
    "Santa Rosa",
    "East New York",
    "Chicoloapan",
    "Vancouver",
    "Sioux Falls",
    "Peoria",
    "Ontario",
    "Jackson",
    "Carolina",
    "Ciudad del Carmen",
    "Chalco",
    "Hollywood",
    "Elk Grove",
    "Springfield",
    "Pembroke Pines",
    "Oakville",
    "Deer Valley",
    "Port Saint Lucie",
    "Salem",
    "Burlington",
    "Corona",
    "Eugene",
    "McKinney",
    "Jiutepec",
    "San Miguel",
    "Fort Collins",
    "Lancaster",
    "Delegacion Cuajimalpa de Morelos",
    "Mejicanos",
    "Salamanca",
    "Cary",
    "San Miguel del Padron",
    "Tempe Junction",
    "Palmdale",
    "Hayward",
    "Centro Habana",
    "San Luis Rio Colorado",
    "San Cristobal de las Casas",
    "Greater Sudbury",
    "Salinas",
    "San Pablo de las Salinas",
    "Frisco",
    "Cuautla",
    "Springfield",
    "San Cristobal",
    "East Chattanooga",
    "Pasadena",
    "Alexandria",
    "Pomona",
    "Ponce",
    "Washington Heights",
    "Lakewood",
    "Ciudad Benito Juarez",
    "Sunnyvale",
    "Abbotsford",
    "Escondido",
    "Kansas City",
    "Chetumal",
    "Piedras Negras",
    "Astoria",
    "Playa del Carmen"
    ]

module.exports =  allCities;